# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [branch1]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: branch1

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: C:\Users\james\Projects\WebStudy\TOP\Foundations\Projects\odin-recipes

      - uses: actions/deploy-pages@v4
        id: deployment
